### PR TITLE
Eliminate version query strings in font asset references

### LINKED ISSUE #174: Version number as URL parameter breaks Content-Type detection
First, sorry if this issue is a dupe, I've check the gem's documentation and previous issues to make to try to find a solution.

-----------

Generated assets include a version number at the number like :

```css
@font-face {
    font-family: 'FontAwesome';
    src: url("/assets/fontawesome-webfont-50bbe9192697e791e2ee4ef73917aeb1b03e727dff08a1fc8d74f00e4aa812e1.eot?v=4.6.3");
 }
```

A page monitoring service we use detected that the Content-Type for this particular asset is returned as `application/octet-stream` instead of `application/font-woff2` for other font assets we use.

As this gem is made to be used with Rails and Sprockets, which generates checksum/hash suffixed assets during compilation that allows for efficient caching, is there a reason for this version parameter ?

Thanks a lot.

### PR DESCRIPTION
**Pull request by rmm5t**
Closes #174

### CODE REVIEW

**Comment by danger89** [comment]
So, does this automatically gets fixed in Bootstrap CDN some day?
https://www.bootstrapcdn.com/fontawesome/

**Comment by rmm5t** [comment]
> So, does this automatically gets fixed in Bootstrap CDN some day?

@danger89 Sorry, this project has nothing to do with the Bootstrap CDN. Because Font-Awesome core itself includes the version numbers, I'm certain Bootstrap CDN will include them as well. 

You're better off taking this up with Font-Awesome core here:
https://github.com/FortAwesome/Font-Awesome/issues/3286

**Comment by danger89** [comment]
So you fixed an issue what isn't fixed upstream?

**Comment by rmm5t** [comment]
> So you fixed an issue what isn't fixed upstream?

Yes and no. The Rails asset pipeline has it's own mechanism for cache busting that we cannot avoid. You can read more about the underlying discussion here:

**Pull request merged**
